
export const PRESSED_CLEAR = "PRESSED_CLEAR";
export const PRESSED_ALL_CLEAR = "PRESSED_ALL_CLEAR";
export const VALUE_KEY_PRESSED = "VALUE_KEY_PRESSED";
export const PROCESS_VALUE_KEY = "PROCESS_VALUE_KEY";
export const STOPPED_DECIMAL = "STOPPED_DECIMAL";
export const STOPPED_LEADING_ZERO = "STOPPED_LEADING_ZERO";
export const EQUAL_KEY = "EQUAL_KEY";
export const PROCESS_EQUAL_KEY = "PROCESS_EQUAL_KEY";
export const PLUS_OPERATOR_KEY_PRESSED = "PLUS_OPERATOR_KEY_PRESSED";
export const MINUS_OPERATOR_KEY_PRESSED = "MINUS_OPERATOR_KEY_PRESSED";
export const MULTIPLY_OPERATOR_KEY_PRESSED = "MULTIPLY_OPERATOR_KEY_PRESSED";
export const DIVIDE_OPERATOR_KEY_PRESSED = "DIVIDE_OPERATOR_KEY_PRESSED";
export const PLUS_MINUS_OPERATOR_KEY_PRESSED = "PLUS_MINUS_OPERATOR_KEY_PRESSED";
export const SQUARED_OPERATOR_KEY_PRESSED = "SQUARED_OPERATOR_KEY_PRESSED";
export const PROCESS_SQUARED_OPERATOR_KEY_PRESSED = "PROCESS_SQUARED_OPERATOR_KEY_PRESSED";
export const PROCESS_OPERATOR_KEY_PRESSED = "PROCESS_OPERATOR_KEY_PRESSED";